version: '2'

services:
  dockerhub-webook:
    image: vangie/dockerhub-webhook
    container_name: ci-dockerhub-webhook
    network_mode: bridge      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./webhooks/dockerhub:/src/scripts
    environment:
      - TOKEN=${DOCKERHUB_TOKEN}
      - VIRTUAL_HOST=dockerhub-webhook.${WEBIDE_CI_DOMAIN}
    restart: always

  nginx:
    image: nginx:alpine
    container_name: ci-nginx
    network_mode: bridge
    ports:
      - "81:80"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    volumes:
      - nginx_conf:/etc/nginx/conf.d
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_webdir:/usr/share/nginx/html
    restart: always

  nginx-gen:
    image: jwilder/docker-gen
    container_name: ci-nginx-gen
    network_mode: bridge
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx_templates:/etc/docker-gen/templates:ro
      - nginx_conf:/etc/nginx/conf.d
      - nginx_certs:/etc/nginx/certs:ro
    command: >-
      -notify-sighup ci-nginx
      -watch -wait 5s:30s
      /etc/docker-gen/templates/nginx.tmpl
      /etc/nginx/conf.d/default.conf
    restart: always

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ci-nginx-letsencrypt
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=ci-nginx-gen"
    volumes:
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_certs:/etc/nginx/certs
      - nginx_webdir:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  entrypoint:
    build: ./entrypoint
    image: webide/ci-entrypoint
    container_name: ci-entrypoint
    network_mode: bridge
    environment:
      - VIRTUAL_HOST=${WEBIDE_CI_DOMAIN}
    restart: always

volumes:
  nginx_conf:
  nginx_vhost:
  nginx_certs:
  nginx_webdir:
